name: test
on:
  pull_request: {}

jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        with:
          script: |
            const check = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'completed',
              head_sha: context.payload.pull_request && context.payload.pull_request.head.sha || context.sha,
              conclusion: 'success',
              name: 'jest-coverage',
              output: {
                  title: 'Jest Coverage',
                  summary: 'All good',
                  text: 'But may be better',
                  annotations: [
                    {
                      path: "src/test.js",
                      start_line: 2,
                      end_line: 2,
                      annotation_level: "notice",
                      message: "Uncovered line"
                    }
                  ]
              }
            })

            const checks = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
            });

            console.log(JSON.stringify(check.data, null ,2))
            console.log(JSON.stringify(checks.data, null, 2))
