name: test
on:
  push: {}
  pull_request: {}

jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const checks = await octokit.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
            });

            console.log(JSON.stringify(checks, null, 2))
